# Aula 07 - Manipulação de Strings com Python

> Uma variável primaria de texto é chamada de char ou caractér possibilitando o armazenamento de 8 bit de memória. Quando necessitamos de um conjunto de caracteres utilizamos um objeto, ou variáveis compostas no caso da maioria das linguagens chamadas de strings. Vamos ver como se aplica. 

In [109]:
frase = "boa tarde a todos"
print(frase)
saudacao = frase[0:9]
print(saudacao)

boa tarde a todos
boa tarde


In [110]:
print(type(frase))
print(type(saudacao))

<class 'str'>
<class 'str'>


In [111]:
print(frase.count(' '))
print(saudacao.count(' '))

3
1


In [112]:
print(len(frase))
print(len(saudacao))

17
9


In [113]:
frase = frase.replace('a todos','galerinha!')
print(frase)
saudacao = saudacao.replace('tarde', 'noite')
print(saudacao)

boa tarde galerinha!
boa noite


In [114]:
frase = [i for i in frase]
print(frase)

['b', 'o', 'a', ' ', 't', 'a', 'r', 'd', 'e', ' ', 'g', 'a', 'l', 'e', 'r', 'i', 'n', 'h', 'a', '!']


In [115]:
for x in frase:
    print(x)

b
o
a
 
t
a
r
d
e
 
g
a
l
e
r
i
n
h
a
!


## Exercício 1

> Crie um código para a seguinte frase: "Sabia que o sabiá sabia assobiar", reparticionado por espaços, após isso crie um print format para visualizar cada palavra em uma coluna separada.

In [116]:
sabia = "Sabia que o sabiá sabia assobiar"
sabia = sabia.replace(' ', '    |    ')
print(sabia)

Sabia    |    que    |    o    |    sabiá    |    sabia    |    assobiar


In [117]:
sabia = "Sabia que o sabiá sabia assobiar"
palavras = sabia.split()

for x in palavras:
    print(x)

Sabia
que
o
sabiá
sabia
assobiar


### Correção

In [118]:
frase = "Sabia que o sabiá sabia assobiar"

palavras = frase.split()

for i in range(max(len(x) for x in palavras)):
    for y in palavras:
        print(y[i] if i < len(y) else ' ', end = ' ')

    print()

S q o s s a 
a u   a a s 
b e   b b s 
i     i i o 
a     á a b 
          i 
          a 
          r 


In [119]:
for i in range(max (len (x) for x in palavras)):
    print(' '.join(x[i] if i<len(x) else ' ' for x in palavras))

S q o s s a
a u   a a s
b e   b b s
i     i i o
a     á a b
          i
          a
          r


# Introdução a Numpy

> Numpy é uma biblioteca python para desenvolvimento de matrizes. tem por objetivos facilitar na criação de algoritmos matemáticos para solucionar paradgimas avançados em relação a arrays. 

In [124]:
pip install numpy

     ---------------------------------------- 0.0/59.7 kB ? eta -:--:--
     ------------- ------------------------ 20.5/59.7 kB 640.0 kB/s eta 0:00:01
     ---------------------------------------- 59.7/59.7 kB 1.1 MB/s eta 0:00:00
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB 1.9 MB/s eta 0:00:07
   ---------------------------------------- 0.1/12.6 MB 1.6 MB/s eta 0:00:08
    --------------------------------------- 0.2/12.6 MB 1.3 MB/s eta 0:00:10
    --------------------------------------- 0.2/12.6 MB 1.4 MB/s eta 0:00:10
    --------------------------------------- 0.3/12.6 MB 1.4 MB/s eta 0:00:10
   - -------------------------------------- 0.4/12.6 MB 1.4 MB/s eta 0:00:09
   - -------------------------------------- 0.4/12.6 MB 1.3 MB/s eta 0:00:10
   - -------------------------------------- 0.5/12.6 MB 1.3 MB/s eta 0:00:10
   - -------------------------------------- 0.5/12.6 MB 1.3 MB/s eta 0:00:10
   - 

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [125]:
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [126]:
b = np.array([(1,2,3), (4,5,6)])
print(b)

[[1 2 3]
 [4 5 6]]


In [127]:
c = np.ones((3,3))
print(c)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [128]:
d = np.eye(5)
print(d)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [131]:
print(a.max())
print(b.max())
print(c.max())


3
6
1.0


In [132]:
print(a.min())
print(b.min())
print(c.min())


1
1
1.0


In [133]:
print(a.sum())
print(b.sum())
print(c.sum())

6
21
9.0


> Para calcular média

In [134]:
print(a.mean())
print(b.mean())
print(c.mean())

2.0
3.5
1.0


> Para desvio padrão

In [138]:
print(round(a.std(),2))
print(round(b.std(),2))
print(round(c.std(),2))

0.82
1.71
0.0


## Exercício 2

> Crie uma matriz chamada contar com os números de 0 até 9. Ao final crie uma contagem, média e desvio padrão dessa matriz. Para adicionar de zero a 9 utilize um for e depois atribua à matriz.

In [149]:
contar = np.array [0,1,2,3,4,5,6,7,8,9]
print(contar)
print(contar.min())
print(contar.max())
print(contar.mean())
print(round(contar.std(),2))

TypeError: 'builtin_function_or_method' object is not subscriptable